/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jackl.gui;

import java.text.DecimalFormat;
import javax.swing.UIManager;

/**
 *
 * @author Fabian
 */
public class GUI extends javax.swing.JFrame {

    private DecimalFormat f;
    private boolean voltageChanged;

    public GUI() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        initAttributes();
        initComponents();
    }

    private void initAttributes() {
        f = new DecimalFormat("#0.00");
        voltageChanged = true;
    }

    private int setVoltageSlider(double volt) {
        System.out.println("setVoltage(" + volt + ");");
        if (volt >= 0 && volt <= 12) //Filter valid Values
        {
            int value = (int) (volt * 100) / 5;
            System.out.println("Filter okay\nValue: " + value);
            voltageSlider.setValue(value);
            voltageChanged = true;
            return value;
        }
        return -1;
    }

    public boolean hasVoltageChanged() {
        if (voltageChanged) {
            voltageChanged = false;
            return true;
        } else {
            return false;
        }
    }

    public void setVoltage(double volt) {
        if (volt >= 0 && volt <= 12) {
            setVoltageSlider(volt);
            voltageTextField.setText(f.format(volt));
            voltageChanged = true;
        }
    }

    public double getVoltage() {
        if (voltageSlider.getValue() * 5 / 100 == Double.parseDouble(voltageTextField.getText())) {
            return voltageSlider.getValue() * 5 / 100;
        }
        return -1;
    }

    public void setCurrent(int current) {
        currentTextField.setText(current + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comButtonGroup = new javax.swing.ButtonGroup();
        voltageTextField = new javax.swing.JTextField();
        currentTextField = new javax.swing.JTextField();
        mALabel = new javax.swing.JLabel();
        voltLabel = new javax.swing.JLabel();
        voltageLabel = new javax.swing.JLabel();
        currentLabel = new javax.swing.JLabel();
        voltageSlider = new javax.swing.JSlider();
        onOffToggleButton = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        settingsMenu = new javax.swing.JMenu();
        connectMenuItem = new javax.swing.JMenuItem();
        comSelectMenu = new javax.swing.JMenu();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem6 = new javax.swing.JRadioButtonMenuItem();
        aboutMenu = new javax.swing.JMenu();
        infoMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PICSU GUI");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 150));
        setMaximumSize(new java.awt.Dimension(2147483647, 150));
        setMinimumSize(new java.awt.Dimension(326, 150));

        voltageTextField.setBackground(new java.awt.Color(255, 255, 153));
        voltageTextField.setColumns(4);
        voltageTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        voltageTextField.setText("6.00");
        voltageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltageTextFieldActionPerformed(evt);
            }
        });

        currentTextField.setEditable(false);
        currentTextField.setBackground(new java.awt.Color(255, 255, 153));
        currentTextField.setColumns(4);
        currentTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        currentTextField.setText("2000");

        mALabel.setLabelFor(currentTextField);
        mALabel.setText("mA");

        voltLabel.setLabelFor(voltageTextField);
        voltLabel.setText("V");

        voltageLabel.setLabelFor(voltageTextField);
        voltageLabel.setText("Voltage");

        currentLabel.setLabelFor(currentTextField);
        currentLabel.setText("Current");

        voltageSlider.setMajorTickSpacing(20);
        voltageSlider.setMaximum(240);
        voltageSlider.setMinimum(20);
        voltageSlider.setMinorTickSpacing(5);
        voltageSlider.setPaintTicks(true);
        voltageSlider.setToolTipText("");
        voltageSlider.setValue(120);
        voltageSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                voltageSliderStateChanged(evt);
            }
        });

        onOffToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        onOffToggleButton.setText("Off");
        onOffToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOffToggleButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 255, 0));
        jTextField1.setColumns(2);
        jTextField1.setToolTipText("");

        settingsMenu.setText("Settings");

        connectMenuItem.setText("Connect");
        settingsMenu.add(connectMenuItem);

        comSelectMenu.setText("Select COM");

        comButtonGroup.add(jRadioButtonMenuItem4);
        jRadioButtonMenuItem4.setText("COM2808");
        comSelectMenu.add(jRadioButtonMenuItem4);

        comButtonGroup.add(jRadioButtonMenuItem5);
        jRadioButtonMenuItem5.setText("COM0893");
        comSelectMenu.add(jRadioButtonMenuItem5);

        comButtonGroup.add(jRadioButtonMenuItem6);
        jRadioButtonMenuItem6.setText("COM1993");
        comSelectMenu.add(jRadioButtonMenuItem6);

        settingsMenu.add(comSelectMenu);

        menuBar.add(settingsMenu);

        aboutMenu.setText("About");

        infoMenuItem.setText("Info");
        aboutMenu.add(infoMenuItem);

        menuBar.add(aboutMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltageSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(onOffToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(voltageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(voltageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mALabel)
                            .addComponent(voltLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voltageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltLabel)
                            .addComponent(voltageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mALabel)
                            .addComponent(currentLabel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(onOffToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(voltageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltageSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_voltageSliderStateChanged
        double value = (voltageSlider.getValue() * 5) / 100.;
        voltageTextField.setText(f.format(value));
        voltageChanged = true;
    }//GEN-LAST:event_voltageSliderStateChanged

    private void onOffToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOffToggleButtonActionPerformed
        if (onOffToggleButton.isSelected()) {
            onOffToggleButton.setText("On ");
        } else {
            onOffToggleButton.setText("Off");
        }
    }//GEN-LAST:event_onOffToggleButtonActionPerformed

    private void voltageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltageTextFieldActionPerformed
        String text = voltageTextField.getText().trim().replace(",", "."); // Replace , with . to fix compatibility with EU Comma
        if (text.contains(".")) {
            if (text.indexOf(".") + 1 <= text.length() - 3) {
                text = text.substring(0, text.length() - 1); //Trim Text if it's too long (eg. 6.255)
            }
        }
        voltageTextField.setText(f.format(setVoltageSlider(Float.parseFloat(text)) * 0.05));
        voltageChanged = true;
    }//GEN-LAST:event_voltageTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.ButtonGroup comButtonGroup;
    private javax.swing.JMenu comSelectMenu;
    private javax.swing.JMenuItem connectMenuItem;
    private javax.swing.JLabel currentLabel;
    private javax.swing.JTextField currentTextField;
    private javax.swing.JMenuItem infoMenuItem;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mALabel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JToggleButton onOffToggleButton;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JLabel voltLabel;
    private javax.swing.JLabel voltageLabel;
    private javax.swing.JSlider voltageSlider;
    private javax.swing.JTextField voltageTextField;
    // End of variables declaration//GEN-END:variables
}
