/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jackl.gui;

import java.text.DecimalFormat;
import javax.swing.UIManager;

/**
 *
 * @author Fabian
 */
public class GUI extends javax.swing.JFrame {

    private DecimalFormat f;

    public GUI() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        initAttributes();
        initComponents();
    }

    private void initAttributes() {
        f = new DecimalFormat("#0.00");
    }

    private int setVoltageSlider(double volt) {
        System.out.println("setVoltage(" + volt + ");");
        if (volt >= 0 && volt <= 12) //Filter valid Values
        {
            int value = (int) (volt * 100) / 5;
            System.out.println("Filter okay\nValue: " + value);
            voltageSlider.setValue(value);
            return value;
        }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltageTextField = new javax.swing.JTextField();
        currentTextField = new javax.swing.JTextField();
        mALabel = new javax.swing.JLabel();
        voltLabel = new javax.swing.JLabel();
        voltageLabel = new javax.swing.JLabel();
        currentLabel = new javax.swing.JLabel();
        voltageSlider = new javax.swing.JSlider();
        onOffToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PICSU GUI");

        voltageTextField.setBackground(new java.awt.Color(255, 255, 153));
        voltageTextField.setColumns(4);
        voltageTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        voltageTextField.setText("6.00");
        voltageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltageTextFieldActionPerformed(evt);
            }
        });

        currentTextField.setEditable(false);
        currentTextField.setBackground(new java.awt.Color(255, 255, 153));
        currentTextField.setColumns(4);
        currentTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        currentTextField.setText("2000");

        mALabel.setLabelFor(currentTextField);
        mALabel.setText("mA");

        voltLabel.setLabelFor(voltageTextField);
        voltLabel.setText("V");

        voltageLabel.setText("Voltage");

        currentLabel.setText("Current");

        voltageSlider.setMajorTickSpacing(20);
        voltageSlider.setMaximum(240);
        voltageSlider.setMinimum(20);
        voltageSlider.setMinorTickSpacing(5);
        voltageSlider.setPaintTicks(true);
        voltageSlider.setToolTipText("");
        voltageSlider.setValue(120);
        voltageSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                voltageSliderStateChanged(evt);
            }
        });

        onOffToggleButton.setBackground(new java.awt.Color(255, 255, 255));
        onOffToggleButton.setText("Off");
        onOffToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOffToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voltageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(voltageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(voltLabel))
                            .addComponent(voltageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(onOffToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(currentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mALabel)
                                .addGap(0, 2, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(currentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voltageLabel)
                            .addComponent(currentLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voltageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(voltLabel)
                            .addComponent(currentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mALabel)))
                    .addComponent(onOffToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltageSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltageSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_voltageSliderStateChanged
        double value = (voltageSlider.getValue() * 5) / 100.;
        voltageTextField.setText(f.format(value));
    }//GEN-LAST:event_voltageSliderStateChanged

    private void onOffToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOffToggleButtonActionPerformed
        if (onOffToggleButton.isSelected()) {
            onOffToggleButton.setText("On ");
        } else {
            onOffToggleButton.setText("Off");
        }
    }//GEN-LAST:event_onOffToggleButtonActionPerformed

    private void voltageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltageTextFieldActionPerformed
        String text = voltageTextField.getText().trim().replace(",", "."); // Replace , with . to fix compatibility with EU Comma
        if (text.contains(".")) {
            if (text.indexOf(".") + 1 <= text.length() - 3) {
                text = text.substring(0, text.length() - 1); //Trim Text if it's too long (eg. 6.255)
            }
        }
        voltageTextField.setText(f.format(setVoltageSlider(Float.parseFloat(text)) * 0.05));
    }//GEN-LAST:event_voltageTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentLabel;
    private javax.swing.JTextField currentTextField;
    private javax.swing.JLabel mALabel;
    private javax.swing.JToggleButton onOffToggleButton;
    private javax.swing.JLabel voltLabel;
    private javax.swing.JLabel voltageLabel;
    private javax.swing.JSlider voltageSlider;
    private javax.swing.JTextField voltageTextField;
    // End of variables declaration//GEN-END:variables
}
